SELECT
    DC.CUSTOMER_UNIQUE_ID,
    ROUND(AVG(FS.PAYMENT_VALUE), 1) AS PAYMENT_VALUE_AVG
FROM JSHODIQ_TECH_TEST.PUBLIC.FACT_SALES AS FS
LEFT JOIN JSHODIQ_TECH_TEST.PUBLIC.DIM_CUSTOMERS AS DC
    ON DC.CUSTOMER_ID = FS.CUSTOMER_ID
GROUP BY 1
ORDER BY 2 DESC