CREATE OR REPLACE TABLE JSHODIQ_TECH_TEST.PUBLIC.DIM_DATE AS
SELECT DISTINCT
    ORDERS.ORDER_ID,
    ORDERS.ORDER_PURCHASE_TIMESTAMP AS ORDER_PURCHASE_TIMESTAMP_G, // step01: customer buy time
    ORDERS.ORDER_ESTIMATED_DELIVERY_DATE, // step02: after purchasing, customer will be informed of this date
    ORDERS.ORDER_APPROVED_AT AS ORDER_APPROVED_AT_G, // step03: payment is approved
    MIN(ORDER_ITEMS.SHIPPING_LIMIT_DATE) AS SHIPPING_LIMIT_DATE, // step04: seller must hand the item to the logistic before this date
    ORDERS.ORDER_DELIVERED_CARRIER_DATE AS ORDER_DELIVERED_CARRIER_DATE_G, // step05: item has been registered in logistic system
    ORDERS.ORDER_DELIVERED_CUSTOMER_DATE AS ORDER_DELIVERED_CUSTOMER_DATE_G, // step06: customer received the item
    ORDERS.ORDER_PURCHASE_TIMESTAMP AS CREATED_AT,
    GREATEST(
        COALESCE(ORDERS.ORDER_PURCHASE_TIMESTAMP, '1970-01-01 00:00:00.000'::TIMESTAMP),
        COALESCE(ORDERS.ORDER_APPROVED_AT, '1970-01-01 00:00:00.000'::TIMESTAMP),
        COALESCE(ORDERS.ORDER_DELIVERED_CARRIER_DATE, '1970-01-01 00:00:00.000'::TIMESTAMP),
        COALESCE(ORDERS.ORDER_DELIVERED_CUSTOMER_DATE, '1970-01-01 00:00:00.000'::TIMESTAMP)
    ) AS UPDATED_AT,
    NULL AS DELETED_AT
FROM JSHODIQ_TECH_TEST.PUBLIC.RAW_ORDER_ITEMS AS ORDER_ITEMS
LEFT JOIN JSHODIQ_TECH_TEST.PUBLIC.RAW_ORDERS AS ORDERS
    ON ORDERS.ORDER_ID = ORDER_ITEMS.ORDER_ID
GROUP BY ORDERS.ORDER_ID, ORDERS.ORDER_PURCHASE_TIMESTAMP, ORDERS.ORDER_ESTIMATED_DELIVERY_DATE, ORDERS.ORDER_APPROVED_AT, ORDERS.ORDER_DELIVERED_CARRIER_DATE, ORDERS.ORDER_DELIVERED_CUSTOMER_DATE