-- SELECT * FROM "JSHODIQ_TECH_TEST"."PUBLIC"."RAW_PAYMENTS" AS "PAYMENTS"
-- WHERE "ORDER_ID" = '001d8f0e34a38c37f7dba2a37d4eba8b'

-- SELECT * FROM "JSHODIQ_TECH_TEST"."PUBLIC"."RAW_ORDERS" AS "ORDERS"

-- SELECT
-- "ORDERS".*
-- FROM "JSHODIQ_TECH_TEST"."PUBLIC"."RAW_ORDERS" AS "ORDERS"

-- SELECT
-- "ORDERS"."ORDER_ID",
-- COUNT(*)
-- FROM "JSHODIQ_TECH_TEST"."PUBLIC"."RAW_ORDER_ITEMS" AS "ORDERS"
-- GROUP BY "ORDERS"."ORDER_ID"
-- ORDER BY COUNT(*) DESC

-- SELECT
-- "ORDERS".*,
-- "ORDERS"."PRICE" + "ORDERS"."FREIGHT_VALUE" AS "P_F_SUM"
-- FROM "JSHODIQ_TECH_TEST"."PUBLIC"."RAW_ORDER_ITEMS" AS "ORDERS"
-- WHERE 1=1
-- AND "ORDERS"."ORDER_ID" = '8272b63d03f5f79c56e9e4120aec44ef'


-- SELECT
-- *
-- FROM "JSHODIQ_TECH_TEST"."PUBLIC"."RAW_ORDERS" AS "ORDERS"
-- WHERE 1=1
-- AND "ORDERS"."ORDER_ID" = '8272b63d03f5f79c56e9e4120aec44ef'


-- SELECT
-- "PAYMENTS"."PAYMENT_ID",
-- COUNT(*)
-- FROM "JSHODIQ_TECH_TEST"."PUBLIC"."RAW_PAYMENTS" AS "PAYMENTS"
-- GROUP BY "PAYMENTS"."PAYMENT_ID"
-- ORDER BY COUNT(*) DESC


-- SELECT
-- CONCAT('ORD', ROW_NUMBER() OVER(ORDER BY "ORDER_ITEMS"."ORDER_ID")) AS "ORDER_ITEM_ID",
-- "ORDER_ITEMS".*
-- FROM "JSHODIQ_TECH_TEST"."PUBLIC"."RAW_ORDER_ITEMS" AS "ORDER_ITEMS"
-- WHERE 1=1

-- SELECT
-- "ORDERS"."ORDER_ID",
-- COUNT(*)
-- FROM "JSHODIQ_TECH_TEST"."PUBLIC"."RAW_ORDER_ITEMS" AS "ORDERS"
-- GROUP BY "ORDERS"."ORDER_ID"
-- HAVING COUNT(*) > 5 AND COUNT(*) < 10
-- ORDER BY RANDOM()
-- LIMIT 5
-- 8272b63d03f5f79c56e9e4120aec44ef
-- 73c8ab38f07dc94389065f7eba4f297a
-- 637617b3ffe9e2f7a2411243829226d0


-- SELECT
-- *
-- FROM "JSHODIQ_TECH_TEST"."PUBLIC"."RAW_ORDER_ITEMS"
-- WHERE 1=1
-- AND "ORDER_ID" = '8272b63d03f5f79c56e9e4120aec44ef'


-- SELECT
-- *
-- FROM "JSHODIQ_TECH_TEST"."PUBLIC"."RAW_PAYMENTS"
-- WHERE 1=1
-- AND "ORDER_ID" = 'fcbe557f2bb4cd2409d67dec35a1e6f3'


-- SELECT
-- "ORDERS"."ORDER_STATUS",
-- COUNT(*)
-- FROM "JSHODIQ_TECH_TEST"."PUBLIC"."RAW_ORDERS" AS "ORDERS"
-- GROUP BY "ORDERS"."ORDER_STATUS"


-- SELECT
-- "PAYMENTS"."PAYMENT_SEQUENTIAL",
-- COUNT(*)
-- FROM "JSHODIQ_TECH_TEST"."PUBLIC"."RAW_PAYMENTS" AS "PAYMENTS"
-- GROUP BY "PAYMENTS"."PAYMENT_SEQUENTIAL" 


-- SELECT * FROM "JSHODIQ_TECH_TEST"."PUBLIC"."RAW_ORDERS"


-- SELECT * FROM "JSHODIQ_TECH_TEST"."PUBLIC"."RAW_ORDERS" WHERE "ORDER_STATUS" = 'created'


-- SELECT
-- "PAYMENTS_S"."ORDER_ID",
-- SUM("PAYMENTS_S"."PAYMENT_VALUE") AS "PAYMENT_VALUE_TOTAL",
-- LISTAGG(CONCAT("PAYMENTS_S"."PAYMENT_TYPE", ' (', "PAYMENTS_S"."PAYMENT_TYPE_COUNT", ') '), ', ') WITHIN GROUP (ORDER BY "PAYMENTS_S"."PAYMENT_TYPE_COUNT" DESC) AS "PAYMENT_TYPE_LIST",
-- MAX("PAYMENTS_S"."PAYMENT_INSTALLMENTS_MAX") AS "PAYMENT_INSTALLMENTS_MAX"
-- FROM
-- (
--     SELECT
--     "PAYMENTS"."ORDER_ID",
--     "PAYMENTS"."PAYMENT_TYPE",
--     COUNT(*) AS "PAYMENT_TYPE_COUNT",
--     SUM("PAYMENTS"."PAYMENT_VALUE") AS "PAYMENT_VALUE",
--     MAX("PAYMENTS"."PAYMENT_INSTALLMENTS") AS "PAYMENT_INSTALLMENTS_MAX"
--     FROM "JSHODIQ_TECH_TEST"."PUBLIC"."RAW_PAYMENTS" AS "PAYMENTS"
--     WHERE 1=1
--     AND "PAYMENTS"."ORDER_ID" = '8554cb37f7158cb0b082a841d24a4589'
--     GROUP BY "PAYMENTS"."ORDER_ID", "PAYMENTS"."PAYMENT_TYPE"
-- ) AS "PAYMENTS_S"
-- GROUP BY "PAYMENTS_S"."ORDER_ID"

-- SELECT * FROM "JSHODIQ_TECH_TEST"."PUBLIC"."RAW_PAYMENTS" AS "PAYMENTS"
-- WHERE "ORDER_ID" = '8554cb37f7158cb0b082a841d24a4589'

-- fa65dad1b0e818e3ccc5cb0e39231352
-- ee9ca989fc93ba09a6eddc250ce01742
-- 4bfcba9e084f46c8e3cb49b0fa6e6159
-- d88e0d5fa41661ce03cf6cf336527646

-- SELECT SUM(PAYMENT_VALUE) FROM JSHODIQ_TECH_TEST.PUBLIC.RAW_PAYMENTS AS PAYMENTS 

-- SELECT
-- DD.ORDER_ID,
-- COUNT(*)
-- FROM JSHODIQ_TECH_TEST.PUBLIC.DIM_DATE AS DD
-- GROUP BY DD.ORDER_ID
-- ORDER BY COUNT(*) DESC

-- SELECT * FROM JSHODIQ_TECH_TEST.PUBLIC.DIM_DATE WHERE ORDER_ID = '62ce4e3989a3477928510bb4d1064cc4'

-- SELECT CUSTOMER_UNIQUE_ID FROM JSHODIQ_TECH_TEST.PUBLIC.DIM_CUSTOMERS AS DC GROUP BY 1
