CREATE OR REPLACE TABLE JSHODIQ_TECH_TEST.PUBLIC.FACT_SALES AS
WITH CTE_PAYMENT_AGGREGATED AS (
    SELECT
        PAYMENTS_S.ORDER_ID,
        -- SUM(PAYMENTS_S.PAYMENT_VALUE) AS PAYMENT_VALUE_TOTAL,
        LISTAGG(CONCAT(PAYMENTS_S.PAYMENT_TYPE, ' (', PAYMENTS_S.PAYMENT_TYPE_COUNT, ') '), ', ')
            WITHIN GROUP (ORDER BY PAYMENTS_S.PAYMENT_TYPE_COUNT DESC) AS PAYMENT_TYPE_LIST,
        MAX(PAYMENTS_S.PAYMENT_INSTALLMENTS_MAX) AS PAYMENT_INSTALLMENTS_MAX
    FROM
    (
        SELECT
            PAYMENTS.ORDER_ID,
            PAYMENTS.PAYMENT_TYPE,
            COUNT(*) AS PAYMENT_TYPE_COUNT,
            -- SUM(PAYMENTS.PAYMENT_VALUE) AS PAYMENT_VALUE,
            MAX(PAYMENTS.PAYMENT_INSTALLMENTS) AS PAYMENT_INSTALLMENTS_MAX
        FROM JSHODIQ_TECH_TEST.PUBLIC.RAW_PAYMENTS AS PAYMENTS
        GROUP BY PAYMENTS.ORDER_ID, PAYMENTS.PAYMENT_TYPE
    ) AS PAYMENTS_S
    GROUP BY PAYMENTS_S.ORDER_ID
)

SELECT
    CONCAT('ORD', ROW_NUMBER() OVER(ORDER BY ORDER_ITEMS.ORDER_ID)) AS ORDER_ITEM_ID_GLOB,
    ORDER_ITEMS.ORDER_ITEM_ID AS ORDER_ITEM_ID_SEQ,
    ORDERS.ORDER_ID,
    ORDER_ITEMS. PRODUCT_ID,
    ORDERS.CUSTOMER_ID,
    ORDERS.ORDER_STATUS,
    ORDER_ITEMS. PRICE,
    ORDER_ITEMS. FREIGHT_VALUE,
    COALESCE(ORDER_ITEMS.PRICE, 0) + COALESCE(ORDER_ITEMS.FREIGHT_VALUE, 0) AS PAYMENT_VALUE,
    PAYMENTS.PAYMENT_TYPE_LIST,
    PAYMENTS.PAYMENT_INSTALLMENTS_MAX
FROM JSHODIQ_TECH_TEST.PUBLIC.RAW_ORDER_ITEMS AS ORDER_ITEMS
LEFT JOIN JSHODIQ_TECH_TEST.PUBLIC.RAW_ORDERS AS ORDERS
    ON ORDERS.ORDER_ID = ORDER_ITEMS.ORDER_ID
LEFT JOIN CTE_PAYMENT_AGGREGATED AS PAYMENTS
    ON PAYMENTS.ORDER_ID = ORDERS.ORDER_ID