SELECT
    TRUNC(DD.ORDER_PURCHASE_TIMESTAMP_G, 'MONTH') AS ORDER_PURCHASE_TIMESTAMP_MONTH,
    COUNT(DC.CUSTOMER_UNIQUE_ID) AS CUSTOMER_ORDER_CREATED_COUNT
FROM JSHODIQ_TECH_TEST.PUBLIC.FACT_SALES AS FS
LEFT JOIN JSHODIQ_TECH_TEST.PUBLIC.DIM_CUSTOMERS AS DC
    ON DC.CUSTOMER_ID = FS.CUSTOMER_ID
LEFT JOIN JSHODIQ_TECH_TEST.PUBLIC.DIM_DATE AS DD
    ON DD.ORDER_ID = FS.ORDER_ID
GROUP BY 1
ORDER BY 1 DESC