SELECT
    DD.ORDER_PURCHASE_TIMESTAMP_G,
    DP.PRODUCT_CATEGORY_NAME,
    FS.PAYMENT_VALUE
FROM JSHODIQ_TECH_TEST.PUBLIC.FACT_SALES AS FS
LEFT JOIN JSHODIQ_TECH_TEST.PUBLIC.DIM_PRODUCTS AS DP
    ON DP.PRODUCT_ID = FS.PRODUCT_ID
LEFT JOIN JSHODIQ_TECH_TEST.PUBLIC.DIM_DATE AS DD
    ON DD.ORDER_ID = FS.ORDER_ID
WHERE 1=1
AND ORDER_PURCHASE_TIMESTAMP_G > DATEADD(DAY, -30, '2018-09-03 09:06:57') // latest 30 days from actual today (2026/02/05) will not return any data. so instead i hardcoded the latest date entry. could replace hardcoded string with CURRENT_DATE()
ORDER BY FS.PAYMENT_VALUE DESC
LIMIT 5