SELECT
    TRUNC(DD.ORDER_PURCHASE_TIMESTAMP_G, 'DAY') AS ORDER_PURCHASE_TIMESTAMP_DAY,
    SUM(FS.PAYMENT_VALUE) AS PAYMENT_VALUE
FROM JSHODIQ_TECH_TEST.PUBLIC.FACT_SALES AS FS
LEFT JOIN JSHODIQ_TECH_TEST.PUBLIC.DIM_DATE AS DD
    ON DD.ORDER_ID = FS.ORDER_ID
GROUP BY 1
ORDER BY 1 DESC